Fix META-INF/some-persistence.xml in tests and remove PersistenceAndQuarkusConfigTest
The failure was not at all what the test expected:

 io.quarkus.deployment.configuration.ConfigurationError: Unable to  properly register the hierarchy of the following JPA classes as they are not in the Jandex index:
     - io.quarkus.examples.common.Clown
   Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin,
   an empty META-INF/beans.xml or quarkus.index-dependency properties.

We're not failing because the persistence unit is configured through
both application.properties and persistence.xml; we're failing
because the class mentioned in persistence.xml does not exist...

So this test is pointless, and we should investigate the matter in more
details as part of another ticket.